### ISSUE TITLE
How about a control structures?

### ISSUE THREAD

**Issue by ZoRDoK** [CREEATION/laravel-elixir-jade#1]
```
@foreach ($users as $user)
    <p>This is user {{ $user->id }}</p>
@endforeach
```

**Comment by CREEATION** [comment]
Hello @ZoRDoK,

could you further explain what you are trying to do?
Jade itself has [iterations functions](http://jade-lang.com/reference/iteration/), you can also pass data to your Jade templates via JSON for example and work with them (iterate over them).
This is just a jade wrapper to compile Jade templates after all, not a Jade/Blade mix :-)

**Comment by cve** [comment]
so, how to do it in jade?

**Comment by CREEATION** [comment]
You can't use your PHP stuff within Jade here, that's not the point of this package. It does only convert your Jade templates to Blade, nothing more. Iteration with Jade is [described here](http://jade-lang.com/reference/iteration/). Maybe you want to use something like [laravel-jade](https://github.com/rvanasperen/laravel-jade)?

**Comment by JaminFarr** [comment]
You can use jade mixins to add blade statements to the jade output

``` jade
mixin blade()
  ='\r\n'
  block
  //- Extra newline for edge cases and pretty: false 
  ='\r\n'
```

e.g.

``` jade
.content
  +blade @yield('main')
```

output

``` html
<div class="content">
@yield('main')

</div>
```

Then you can build up the mixins from there and use the jade indentation to close loops

``` jade
mixin foreach(terms)
  +blade @foreach(#{terms})
  block
  +blade @endforeach
```

input

``` jade
.userlist
  +foreach('$users as $user')
    p Name: {{ $user->name }}
```

output

``` html
<div class="userlist">
@foreach($users as $user)

  <p>Name: {{ $user->name }}</p>
@endforeach

</div>
```

**Comment by JaminFarr** [comment]
I've made a gist with mixins for most of the blade statments https://gist.github.com/JaminFarr/0b875916b39bf83c4b06

**Comment by CREEATION** [comment]
Cool, thanks @JaminFarr!
Mind if I add a link to your gist to the readme? :+1:

**Comment by JaminFarr** [comment]
Yes, thanks.

I did do a searching after and found another already made set of mixins https://gist.github.com/franzose/280218e54f559040039f

**Comment by CREEATION** [comment]
@franzose May I add your gist to the readme, too?

**Comment by franzose** [comment]
@CREEATION of course! Glad to know someone found it useful)

**Comment by CREEATION** [comment]
Awesome :+1:
I close the issue for now. Thanks all for your input :-)
