### ISSUE TITLE
Configure extensions

### ISSUE THREAD

**Issue by sebestenyb** [CREEATION/laravel-elixir-jade#10]
Hi

It would be awesome, if the produced extension could be configured.
Right now it's locked to `php` or `blade.php`.

If we could specify an extension instead of having a `blade:true` , maybe defaulting to `blade.php` it could be used to compile both backend and front-end templates, like AngularJS, etc.

Cheers, Sebi

**Comment by lazytyper** [comment]
It's not possible to specify any extension.
Just add `"extension": "html"` or any other extension to the options.
