### ISSUE TITLE
Use gulp-jade-find-affected

### ISSUE THREAD

**Issue by lazytyper** [CREEATION/laravel-elixir-jade#12]
`gulp watch` always compiles all .jade files if one has been modified,

You should use [gulp-jade-find-affected](https://github.com/teltploek/gulp-jade-find-affected) in the pipe I tried it, but did not get it to work yet.

**Comment by mastito03** [comment]
waiting for merge #11

**Comment by lazytyper** [comment]
@mastito03 
Your fork seems not to work as it should yet.
I got a file `frontend.jade` which includes `frontend-menu.jade` by

``` jade
   include frontend-menu
```

`gulp watch` now only compiles the "frontend-menu.jade" into blade, but it should compile "frontend.jade", too, because it depends on it.

**Comment by mastito03** [comment]
It work on me.
I have `_mixin.jade` which included in most of jade file in my project. And all file include it was compiled

I have update it, so it now show which file have been compiled

**Comment by lazytyper** [comment]
My `frontend.jade` and `frontend_menu.jade` were both in a sub folder `layouts/`. if both are in the root folder, then it works.
Maybe this is a bug in `gulp-jade-find-affected` ?

**Comment by mastito03** [comment]
I think where are files located is not the problem. because all my files are located in different folder.

can you show me the log??

**Comment by eschmid72** [comment]
do you have Teamviewer?

**Comment by lazytyper** [comment]
-> [https://github.com/teltploek/gulp-jade-find-affected/issues/4]

**Comment by mastito03** [comment]
replace teltploek/gulp-jade-find-affected with juanfran/gulp-jade-inheritance
it work better

**Comment by lazytyper** [comment]
@mastito03 
Cool, it works as it should now. Thank you, Benedict!
