### ISSUE TITLE
New files are not getting compiled when running gulp watch in the background

### ISSUE THREAD

**Issue by spaceemotion** [CREEATION/laravel-elixir-jade#2]
I recently noticed that I have to restart my gulp script whenever I add a new file to my jade files. Is that a general problem with gulp or can this be fixed in this elixir-addon?

**Comment by CREEATION** [comment]
This is a general "problem" with gulp.watch.
See [this stackoverflow answer](http://stackoverflow.com/a/22391756) for more information.
