### ISSUE TITLE
allow mixin to be auto included in jade

### ISSUE THREAD

**Issue by tomas02061991** [CREEATION/laravel-elixir-jade#20]
really nice plugin

I was wondering if it is possible to add an option to write an include statement in all the jade file as the compile for mixins?

example:

```
mix.jade({
  mixins: ['mixins/*.jade']
});
```

for all jades found it will take all jade files it compiles and add a:

```
include /path/to/mixins/test.jade
include /path/to/mixins/test2.jade
```

to the top of the jade file, before they compile.

i hope I made myself understandable.

**Comment by lazytyper** [comment]
Try this here:

https://github.com/BKWLD/laravel-pug
