### ISSUE TITLE
this should be @deprecated

### ISSUE THREAD

**Issue by lazytyper** [CREEATION/laravel-elixir-jade#21]
and referring to this:

https://github.com/mrkmg/laravel-elixir-pug
(https://www.npmjs.com/package/laravel-elixir-pug)

or better use:

https://github.com/BKWLD/laravel-pug (I did not have time to try it yet, but looks great)

**Comment by CREEATION** [comment]
Better late than never, I guess. Added a deprecation warning to the npm package.
Will update the readme accordingly.
