### ISSUE TITLE
the "basedir" option is required to use "include" with "absolute" paths

### ISSUE THREAD

**Issue by tomexx** [CREEATION/laravel-elixir-jade#5]
Hi,
I have a problem. I try to include a file with mixins using an absolute path, but I am getting following error:
"the "basedir" option is required to use "include" with "absolute" paths"

However, .jade method in my gulpfile.js contains a defined basedir (it should be the default value anyway):
mix.jade({
            baseDir: './resources',
            pretty: true
        })

Mixins work as expected when I use relative path.
Thx for inspecting this issue.

**Comment by CREEATION** [comment]
Hey @tomexx,

currently I'm not actively using laravel-elixir-jade in any project (switched to gulp, because it offers more control over everything and Elixir is quite limiting).
Therefore I'd be happy for any pull requests :-)
- Thomas

**Comment by wlkns** [comment]
I went to fork this to work on a patch for this issue but it seems someone has already done it.

This issue is fixed?

**Comment by CREEATION** [comment]
If @tomexx can confirm that it's fixed (although there weren't any pull requests lately), then I close this issue. Thanks for looking into it @arkin- :)

**Comment by CREEATION** [comment]
@tomexx Any news on this?
