### ISSUE TITLE
[Breaking] Does not seem to work with latest elixir ^3.0

### ISSUE THREAD

**Issue by spaceemotion** [CREEATION/laravel-elixir-jade#8]
Version 3.0 introduced a new extensions system, which is why this extension sadly is no longer working with the newest elixir one.

**Comment by CREEATION** [comment]
Duplicate of https://github.com/CREEATION/laravel-elixir-jade/issues/7

**Comment by spaceemotion** [comment]
oh seems like I wrote this, didn't submit, and another one opened another ticket while I was out of home for a quick time :)

**Comment by CREEATION** [comment]
no problem =)
